  version: "3.9"
  name: developing
  services:
    nginx:
      image: nginx
      ports:
        - "80:80"
      volumes:
        - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./:/var/www/html
      links:
        - php
    php:
      image: php:8.2-fpm
      working_dir: /var/www/html
      volumes:
        - ./:/var/www/html

    composer:
      image: composer
      volumes:
        - ".:/app"